### ISSUE TITLE
管理员账号未插入到user_info中

### ISSUE THREAD

**Issue by Vancir** [Vancir/SSMS#10]
管理员账号 admin 并未插入到user_info中, 在登录时验证会提取出user_info中的uID字段跟用户提交的账号比对. 发现没有, 而导致管理员账号无法登录 @Jeffchan9717 请提出一个合理的解决方案

**Comment by Jeffchan9717** [comment]
admin是唯一需要人工创建的账户，

**Comment by Jeffchan9717** [comment]
在一个新用户注册时（学生或老师）
应该以admin身份登录，然后调用admin_insert_user_info()创建该用户

**Comment by Jeffchan9717** [comment]
以root@localhost身份登录
执行INSERT  INTO user_info() VALUES(‘admin’, '123456', 2, LAST_insert_ID());
'123456'应改为对应密码
2是身份字段，我用2表示管理员（0学生，1教师）
LAST_insert_ID()会返回该字段AUTO_INCREMENT的最新值

**Comment by Jeffchan9717** [comment]
We have resolved the problem which is due to the [password policy] which bring failure when creating user with weak password, thus no user is created when we think it should.
To resolve this, we drop the policy as root.
This issue might be closed.

**Comment by Jeffchan9717** [comment]
I resolved the issue by adding
`INSERT INTO user_info VALUES('admin', '2Htz$6PLmV0x54xa', 2, 0);`
in the root.sql
This issue might be closed.
