### ISSUE TITLE
学生/教师账号无法访问mysql数据库

### ISSUE THREAD

**Issue by Vancir** [Vancir/SSMS#11]
当我以学生用户vancir登录时, 发现该账号无法连接mysql. 原因是虽然该账户存在于user_info中, 但并未真正在mysql.user建立用户.
```
select user from mysql.user
+------------------+
| user             |
+------------------+
| admin            |
| debian-sys-maint |
| mysql.infoschema |
| mysql.session    |
| mysql.sys        |
| root             |
| 张三             |
| 张伟             |
+------------------+
```

**Comment by Jeffchan9717** [comment]
We have resolved the problem which is due to the [password policy] which bring failure when creating user with weak password, thus no user is created when we think it should.
To resolve this, we drop the policy as root.
This issue might be closed.
