### ISSUE TITLE
简化sql脚本

### ISSUE THREAD

**Issue by Vancir** [Vancir/SSMS#4]
由于是从mysql直接导出, 因此以下sql脚本并不够简洁
- alldb.sql
- school.sql
请阅读上述sql脚本, 将其中有用的sql命令保留, 无用信息剔除. 使脚本可读性较好

**Comment by Vancir** [comment]
我将对应的sql脚本整理放进sql/目录下, 并在README.md添加了对应说明. 但是文件夹sql/下的脚本都是不完整的, 仅用于我个人测试. 因此 @Jeffchan9717 需要你来进一步整合完善.

**Comment by Jeffchan9717** [comment]
We have resolved the problem by changing design pattern, thus this issue might be closed
